load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//:__subpackages__"])

licenses(["notice"])

cc_library(
    name = "composite_ml_dsa_sign_boringssl",
    srcs = ["composite_ml_dsa_sign_boringssl.cc"],
    hdrs = ["composite_ml_dsa_sign_boringssl.h"],
    include_prefix = "tink/signature/subtle",
    deps = [
        "//tink:low_level_crypto_access_token",
        "//tink:public_key_sign",
        "//tink/internal:fips_utils",
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_private_key",
        "//tink/signature:ecdsa_private_key",
        "//tink/signature:ed25519_private_key",
        "//tink/signature:rsa_ssa_pkcs1_private_key",
        "//tink/signature:rsa_ssa_pss_private_key",
        "//tink/signature/internal:composite_ml_dsa_util_boringssl",
        "//tink/signature/internal:ml_dsa_sign_boringssl",
        "//tink/subtle:ecdsa_sign_boringssl",
        "//tink/subtle:ed25519_sign_boringssl",
        "//tink/subtle:rsa_ssa_pkcs1_sign_boringssl",
        "//tink/subtle:rsa_ssa_pss_sign_boringssl",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
    ],
)

cc_test(
    name = "composite_ml_dsa_sign_boringssl_test",
    srcs = ["composite_ml_dsa_sign_boringssl_test.cc"],
    deps = [
        ":composite_ml_dsa_sign_boringssl",
        "//tink:low_level_crypto_access",
        "//tink:public_key_sign",
        "//tink/internal:fips_utils",
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_private_key",
        "//tink/signature/internal/testing:composite_ml_dsa_test_util",
        "//tink/util:test_matchers",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "composite_ml_dsa_verify_boringssl",
    srcs = ["composite_ml_dsa_verify_boringssl.cc"],
    hdrs = ["composite_ml_dsa_verify_boringssl.h"],
    include_prefix = "tink/signature/subtle",
    deps = [
        "//tink:low_level_crypto_access_token",
        "//tink:public_key_verify",
        "//tink/internal:fips_utils",
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_public_key",
        "//tink/signature:ecdsa_public_key",
        "//tink/signature:ed25519_public_key",
        "//tink/signature:rsa_ssa_pkcs1_public_key",
        "//tink/signature:rsa_ssa_pss_public_key",
        "//tink/signature/internal:composite_ml_dsa_util_boringssl",
        "//tink/signature/internal:ml_dsa_verify_boringssl",
        "//tink/subtle:ecdsa_verify_boringssl",
        "//tink/subtle:ed25519_verify_boringssl",
        "//tink/subtle:rsa_ssa_pkcs1_verify_boringssl",
        "//tink/subtle:rsa_ssa_pss_verify_boringssl",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@boringssl//:crypto",
    ],
)

cc_test(
    name = "composite_ml_dsa_verify_boringssl_test",
    srcs = ["composite_ml_dsa_verify_boringssl_test.cc"],
    deps = [
        ":composite_ml_dsa_sign_boringssl",
        ":composite_ml_dsa_verify_boringssl",
        "//tink:low_level_crypto_access",
        "//tink:public_key_sign",
        "//tink:public_key_verify",
        "//tink/internal:fips_utils",
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_private_key",
        "//tink/signature/internal/testing:composite_ml_dsa_test_util",
        "//tink/signature/internal/testing:composite_ml_dsa_test_vectors",
        "//tink/signature/internal/testing:signature_test_vector",
        "//tink/util:test_matchers",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_ecdsa_key",
    srcs = ["create_ecdsa_key.cc"],
    hdrs = ["create_ecdsa_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:ecdsa_parameters",
        "//tink/signature:ecdsa_private_key",
        "//tink/signature/internal:ecdsa_key_creator",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_ecdsa_key_test",
    srcs = ["create_ecdsa_key_test.cc"],
    deps = [
        ":create_ecdsa_key",
        "//tink/signature:ecdsa_parameters",
        "//tink/signature:ecdsa_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_ed25519_key",
    srcs = ["create_ed25519_key.cc"],
    hdrs = ["create_ed25519_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:ed25519_parameters",
        "//tink/signature:ed25519_private_key",
        "//tink/signature/internal:ed25519_key_creator",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_ed25519_key_test",
    srcs = ["create_ed25519_key_test.cc"],
    deps = [
        ":create_ed25519_key",
        "//tink:partial_key_access",
        "//tink/signature:ed25519_parameters",
        "//tink/signature:ed25519_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_rsa_ssa_pkcs1_key",
    srcs = ["create_rsa_ssa_pkcs1_key.cc"],
    hdrs = ["create_rsa_ssa_pkcs1_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:rsa_ssa_pkcs1_parameters",
        "//tink/signature:rsa_ssa_pkcs1_private_key",
        "//tink/signature/internal:rsa_ssa_pkcs1_key_creator",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_rsa_ssa_pkcs1_key_test",
    srcs = ["create_rsa_ssa_pkcs1_key_test.cc"],
    deps = [
        ":create_rsa_ssa_pkcs1_key",
        "//tink:partial_key_access",
        "//tink/signature:rsa_ssa_pkcs1_parameters",
        "//tink/signature:rsa_ssa_pkcs1_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_rsa_ssa_pss_key",
    srcs = ["create_rsa_ssa_pss_key.cc"],
    hdrs = ["create_rsa_ssa_pss_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:rsa_ssa_pss_parameters",
        "//tink/signature:rsa_ssa_pss_private_key",
        "//tink/signature/internal:rsa_ssa_pss_key_creator",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_rsa_ssa_pss_key_test",
    srcs = ["create_rsa_ssa_pss_key_test.cc"],
    deps = [
        ":create_rsa_ssa_pss_key",
        "//tink:partial_key_access",
        "//tink/signature:rsa_ssa_pss_parameters",
        "//tink/signature:rsa_ssa_pss_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_ml_dsa_key",
    srcs = ["create_ml_dsa_key.cc"],
    hdrs = ["create_ml_dsa_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:ml_dsa_parameters",
        "//tink/signature:ml_dsa_private_key",
        "//tink/signature/internal:ml_dsa_key_creator",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_ml_dsa_key_test",
    srcs = ["create_ml_dsa_key_test.cc"],
    deps = [
        ":create_ml_dsa_key",
        "//tink:partial_key_access",
        "//tink/signature:ml_dsa_parameters",
        "//tink/signature:ml_dsa_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "create_composite_ml_dsa_key",
    srcs = ["create_composite_ml_dsa_key.cc"],
    hdrs = ["create_composite_ml_dsa_key.h"],
    include_prefix = "tink/signature/subtle",
    visibility = ["//visibility:public"],
    deps = [
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_private_key",
        "//tink/signature/internal:composite_ml_dsa_key_creator",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "create_composite_ml_dsa_key_test",
    srcs = ["create_composite_ml_dsa_key_test.cc"],
    deps = [
        ":create_composite_ml_dsa_key",
        "//tink/signature:composite_ml_dsa_parameters",
        "//tink/signature:composite_ml_dsa_private_key",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)
