// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

// *****************************************************************************
// ************* Generated by tink_proto_generator.h DO NOT EDIT! **************
// *****************************************************************************
#ifndef THIRD_PARTY_TINK_PROTO_COMMON_TINKPB_H_
#define THIRD_PARTY_TINK_PROTO_COMMON_TINKPB_H_

// NOLINTBEGIN
// clang-format off

namespace google::crypto::tink::internal {

inline bool EllipticCurveTypeTP_IsValid(int value) {
  switch (value) {
    case 0:  // kUnknownCurve
    case 2:  // kNistP256
    case 3:  // kNistP384
    case 4:  // kNistP521
    case 5:  // kCurve25519
      return true;
    default:
      return false;
  }
}

enum class EllipticCurveTypeTP : int {
  kUnknownCurve = 0,
  kNistP256 = 2,
  kNistP384 = 3,
  kNistP521 = 4,
  kCurve25519 = 5,
};
inline bool EcPointFormatTP_IsValid(int value) {
  switch (value) {
    case 0:  // kUnknownFormat
    case 1:  // kUncompressed
    case 2:  // kCompressed
    case 3:  // kDoNotUseCrunchyUncompressed
      return true;
    default:
      return false;
  }
}

enum class EcPointFormatTP : int {
  kUnknownFormat = 0,
  kUncompressed = 1,
  kCompressed = 2,
  kDoNotUseCrunchyUncompressed = 3,
};
inline bool HashTypeTP_IsValid(int value) {
  switch (value) {
    case 0:  // kUnknownHash
    case 1:  // kSha1
    case 2:  // kSha384
    case 3:  // kSha256
    case 4:  // kSha512
    case 5:  // kSha224
      return true;
    default:
      return false;
  }
}

enum class HashTypeTP : int {
  kUnknownHash = 0,
  kSha1 = 1,
  kSha384 = 2,
  kSha256 = 3,
  kSha512 = 4,
  kSha224 = 5,
};
}  // namespace google::crypto::tink::internal

// clang-format on
// NOLINTEND

#endif  // THIRD_PARTY_TINK_PROTO_COMMON_TINKPB_H_
