// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

// *****************************************************************************
// ************* Generated by tink_proto_generator.h DO NOT EDIT! **************
// *****************************************************************************
#ifndef THIRD_PARTY_TINK_PROTO_HMAC_TINKPB_H_
#define THIRD_PARTY_TINK_PROTO_HMAC_TINKPB_H_

// NOLINTBEGIN
// clang-format off

#include "tink/internal/proto_parser_enum_field.h"
#include "tink/internal/proto_parser_field.h"
#include "tink/internal/proto_parser_message.h"
#include "tink/internal/proto_parser_options.h"
#include "tink/internal/proto_parser_scalar_fields.h"
#include "tink/internal/proto_parser_secret_data_field.h"
#include "tink/secret_data.h"
#include "proto/common.tinkpb.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>

namespace google::crypto::tink::internal {

class HmacParamsTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  HmacParamsTP() = default;

  HmacParamsTP(HmacParamsTP&&) = default;
  HmacParamsTP& operator=(HmacParamsTP&&) = default;
  HmacParamsTP(const HmacParamsTP&) = default;
  HmacParamsTP& operator=(const HmacParamsTP&) = default;

  void clear_hash() {
    hash_.Clear();
  }
  ::google::crypto::tink::internal::HashTypeTP hash() const {
    return hash_.value();
  }
  void set_hash(::google::crypto::tink::internal::HashTypeTP value) {
    hash_.set_value(value);
  }

  void clear_tag_size() {
    tag_size_.Clear();
  }
  uint32_t tag_size() const {
    return tag_size_.value();
  }
  void set_tag_size(uint32_t value) {
    tag_size_.set_value(value);
  }

  void MergeFrom(const HmacParamsTP& other) {
    hash_.set_value(other.hash());
    tag_size_.set_value(other.tag_size());
  }

  void CopyFrom(const HmacParamsTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 2; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      2>{&hash_, &tag_size_}[i];
  }

  ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::HashTypeTP> hash_{
      1, &::google::crypto::tink::internal::HashTypeTP_IsValid, ::google::crypto::tink::internal::HashTypeTP::kUnknownHash,
      ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::Uint32Field tag_size_{2, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
};
class HmacKeyTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  HmacKeyTP() = default;

  HmacKeyTP(HmacKeyTP&&) = default;
  HmacKeyTP& operator=(HmacKeyTP&&) = default;
  HmacKeyTP(const HmacKeyTP&) = default;
  HmacKeyTP& operator=(const HmacKeyTP&) = default;

  void clear_version() {
    version_.Clear();
  }
  uint32_t version() const {
    return version_.value();
  }
  void set_version(uint32_t value) {
    version_.set_value(value);
  }

  bool has_params() const {
    return params_.has_value();
  }
  void clear_params() {
    params_.Clear();
  }
  ::google::crypto::tink::internal::HmacParamsTP* mutable_params() {
    return params_.mutable_value();
  }
  const ::google::crypto::tink::internal::HmacParamsTP& params() const {
    return params_.value();
  }

  void clear_key_value() {
    key_value_.Clear();
  }
  ::crypto::tink::SecretData* mutable_key_value() {
    return key_value_.mutable_value();
  }
  const ::crypto::tink::SecretData& key_value() const {
    return key_value_.value();
  }
  void set_key_value(::crypto::tink::SecretData value) {
    *key_value_.mutable_value() = std::move(value);
  }

  void MergeFrom(const HmacKeyTP& other) {
    version_.set_value(other.version());
    if (other.has_params()) {
      params_.mutable_value()->MergeFrom(other.params());
    }
    *key_value_.mutable_value() = other.key_value();
  }

  void CopyFrom(const HmacKeyTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 3; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      3>{&version_, &params_, &key_value_}[i];
  }

  ::crypto::tink::internal::proto_parsing::Uint32Field version_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::MessageField<::google::crypto::tink::internal::HmacParamsTP> params_{2, ::crypto::tink::internal::ProtoFieldOptions::kExplicit};
  ::crypto::tink::internal::proto_parsing::SecretDataField key_value_{3, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
};
class HmacKeyFormatTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  HmacKeyFormatTP() = default;

  HmacKeyFormatTP(HmacKeyFormatTP&&) = default;
  HmacKeyFormatTP& operator=(HmacKeyFormatTP&&) = default;
  HmacKeyFormatTP(const HmacKeyFormatTP&) = default;
  HmacKeyFormatTP& operator=(const HmacKeyFormatTP&) = default;

  bool has_params() const {
    return params_.has_value();
  }
  void clear_params() {
    params_.Clear();
  }
  ::google::crypto::tink::internal::HmacParamsTP* mutable_params() {
    return params_.mutable_value();
  }
  const ::google::crypto::tink::internal::HmacParamsTP& params() const {
    return params_.value();
  }

  void clear_key_size() {
    key_size_.Clear();
  }
  uint32_t key_size() const {
    return key_size_.value();
  }
  void set_key_size(uint32_t value) {
    key_size_.set_value(value);
  }

  void clear_version() {
    version_.Clear();
  }
  uint32_t version() const {
    return version_.value();
  }
  void set_version(uint32_t value) {
    version_.set_value(value);
  }

  using ::crypto::tink::internal::proto_parsing::Message::SerializeAsString;

  void MergeFrom(const HmacKeyFormatTP& other) {
    if (other.has_params()) {
      params_.mutable_value()->MergeFrom(other.params());
    }
    key_size_.set_value(other.key_size());
    version_.set_value(other.version());
  }

  void CopyFrom(const HmacKeyFormatTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 3; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      3>{&params_, &key_size_, &version_}[i];
  }

  ::crypto::tink::internal::proto_parsing::MessageField<::google::crypto::tink::internal::HmacParamsTP> params_{1, ::crypto::tink::internal::ProtoFieldOptions::kExplicit};
  ::crypto::tink::internal::proto_parsing::Uint32Field key_size_{2, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::Uint32Field version_{3, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
};
}  // namespace google::crypto::tink::internal

// clang-format on
// NOLINTEND

#endif  // THIRD_PARTY_TINK_PROTO_HMAC_TINKPB_H_
