// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

// *****************************************************************************
// ************* Generated by tink_proto_generator.h DO NOT EDIT! **************
// *****************************************************************************
#ifndef THIRD_PARTY_TINK_PROTO_TINK_TINKPB_H_
#define THIRD_PARTY_TINK_PROTO_TINK_TINKPB_H_

// NOLINTBEGIN
// clang-format off

#include "absl/strings/string_view.h"
#include "tink/internal/proto_parser_enum_field.h"
#include "tink/internal/proto_parser_field.h"
#include "tink/internal/proto_parser_message.h"
#include "tink/internal/proto_parser_options.h"
#include "tink/internal/proto_parser_scalar_fields.h"
#include "tink/internal/proto_parser_secret_data_field.h"
#include "tink/secret_data.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>

namespace google::crypto::tink::internal {

inline bool KeyStatusTypeTP_IsValid(int value) {
  switch (value) {
    case 0:  // kUnknownStatus
    case 1:  // kEnabled
    case 2:  // kDisabled
    case 3:  // kDestroyed
      return true;
    default:
      return false;
  }
}

enum class KeyStatusTypeTP : int {
  kUnknownStatus = 0,
  kEnabled = 1,
  kDisabled = 2,
  kDestroyed = 3,
};
inline bool OutputPrefixTypeTP_IsValid(int value) {
  switch (value) {
    case 0:  // kUnknownPrefix
    case 1:  // kTink
    case 2:  // kLegacy
    case 3:  // kRaw
    case 4:  // kCrunchy
    case 5:  // kWithIdRequirement
      return true;
    default:
      return false;
  }
}

enum class OutputPrefixTypeTP : int {
  kUnknownPrefix = 0,
  kTink = 1,
  kLegacy = 2,
  kRaw = 3,
  kCrunchy = 4,
  kWithIdRequirement = 5,
};
class KeyTemplateTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  KeyTemplateTP() = default;

  KeyTemplateTP(KeyTemplateTP&&) = default;
  KeyTemplateTP& operator=(KeyTemplateTP&&) = default;
  KeyTemplateTP(const KeyTemplateTP&) = default;
  KeyTemplateTP& operator=(const KeyTemplateTP&) = default;

  void clear_type_url() {
    type_url_.Clear();
  }
  std::string* mutable_type_url() {
    return type_url_.mutable_value();
  }
  const std::string& type_url() const {
    return type_url_.value();
  }
  void set_type_url(absl::string_view value) {
    type_url_.set_value(value);
  }

  void clear_value() {
    value_.Clear();
  }
  std::string* mutable_value() {
    return value_.mutable_value();
  }
  const std::string& value() const {
    return value_.value();
  }
  void set_value(absl::string_view value) {
    value_.set_value(value);
  }

  void clear_output_prefix_type() {
    output_prefix_type_.Clear();
  }
  ::google::crypto::tink::internal::OutputPrefixTypeTP output_prefix_type() const {
    return output_prefix_type_.value();
  }
  void set_output_prefix_type(::google::crypto::tink::internal::OutputPrefixTypeTP value) {
    output_prefix_type_.set_value(value);
  }

  using ::crypto::tink::internal::proto_parsing::Message::SerializeAsString;

  void MergeFrom(const KeyTemplateTP& other) {
    type_url_.set_value(other.type_url());
    value_.set_value(other.value());
    output_prefix_type_.set_value(other.output_prefix_type());
  }

  void CopyFrom(const KeyTemplateTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 3; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      3>{&type_url_, &value_, &output_prefix_type_}[i];
  }

  ::crypto::tink::internal::proto_parsing::BytesField type_url_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::BytesField value_{2, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::OutputPrefixTypeTP> output_prefix_type_{
      3, &::google::crypto::tink::internal::OutputPrefixTypeTP_IsValid, ::google::crypto::tink::internal::OutputPrefixTypeTP::kUnknownPrefix,
      ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
};
class KeyDataTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:

  static bool KeyMaterialTypeTP_IsValid(int value) {
    switch (value) {
      case 0:  // kUnknownKeymaterial
      case 1:  // kSymmetric
      case 2:  // kAsymmetricPrivate
      case 3:  // kAsymmetricPublic
      case 4:  // kRemote
        return true;
      default:
        return false;
    }
  }

  enum class KeyMaterialTypeTP : int {
    kUnknownKeymaterial = 0,
    kSymmetric = 1,
    kAsymmetricPrivate = 2,
    kAsymmetricPublic = 3,
    kRemote = 4,
  };
  KeyDataTP() = default;

  KeyDataTP(KeyDataTP&&) = default;
  KeyDataTP& operator=(KeyDataTP&&) = default;
  KeyDataTP(const KeyDataTP&) = default;
  KeyDataTP& operator=(const KeyDataTP&) = default;

  void clear_type_url() {
    type_url_.Clear();
  }
  std::string* mutable_type_url() {
    return type_url_.mutable_value();
  }
  const std::string& type_url() const {
    return type_url_.value();
  }
  void set_type_url(absl::string_view value) {
    type_url_.set_value(value);
  }

  void clear_value() {
    value_.Clear();
  }
  ::crypto::tink::SecretData* mutable_value() {
    return value_.mutable_value();
  }
  const ::crypto::tink::SecretData& value() const {
    return value_.value();
  }
  void set_value(::crypto::tink::SecretData value) {
    *value_.mutable_value() = std::move(value);
  }

  void clear_key_material_type() {
    key_material_type_.Clear();
  }
  ::google::crypto::tink::internal::KeyDataTP::KeyMaterialTypeTP key_material_type() const {
    return key_material_type_.value();
  }
  void set_key_material_type(::google::crypto::tink::internal::KeyDataTP::KeyMaterialTypeTP value) {
    key_material_type_.set_value(value);
  }

  void MergeFrom(const KeyDataTP& other) {
    type_url_.set_value(other.type_url());
    *value_.mutable_value() = other.value();
    key_material_type_.set_value(other.key_material_type());
  }

  void CopyFrom(const KeyDataTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 3; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      3>{&type_url_, &value_, &key_material_type_}[i];
  }

  ::crypto::tink::internal::proto_parsing::BytesField type_url_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::SecretDataField value_{2, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::KeyDataTP::KeyMaterialTypeTP> key_material_type_{
      3, &::google::crypto::tink::internal::KeyDataTP::KeyMaterialTypeTP_IsValid, ::google::crypto::tink::internal::KeyDataTP::KeyMaterialTypeTP::kUnknownKeymaterial,
      ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
};
class KeysetTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  class KeyTP : public ::crypto::tink::internal::proto_parsing::Message {
   public:
    KeyTP() = default;

    KeyTP(KeyTP&&) = default;
    KeyTP& operator=(KeyTP&&) = default;
    KeyTP(const KeyTP&) = default;
    KeyTP& operator=(const KeyTP&) = default;

    bool has_key_data() const {
      return key_data_.has_value();
    }
    void clear_key_data() {
      key_data_.Clear();
    }
    ::google::crypto::tink::internal::KeyDataTP* mutable_key_data() {
      return key_data_.mutable_value();
    }
    const ::google::crypto::tink::internal::KeyDataTP& key_data() const {
      return key_data_.value();
    }

    void clear_status() {
      status_.Clear();
    }
    ::google::crypto::tink::internal::KeyStatusTypeTP status() const {
      return status_.value();
    }
    void set_status(::google::crypto::tink::internal::KeyStatusTypeTP value) {
      status_.set_value(value);
    }

    void clear_key_id() {
      key_id_.Clear();
    }
    uint32_t key_id() const {
      return key_id_.value();
    }
    void set_key_id(uint32_t value) {
      key_id_.set_value(value);
    }

    void clear_output_prefix_type() {
      output_prefix_type_.Clear();
    }
    ::google::crypto::tink::internal::OutputPrefixTypeTP output_prefix_type() const {
      return output_prefix_type_.value();
    }
    void set_output_prefix_type(::google::crypto::tink::internal::OutputPrefixTypeTP value) {
      output_prefix_type_.set_value(value);
    }

    void MergeFrom(const KeyTP& other) {
      if (other.has_key_data()) {
        key_data_.mutable_value()->MergeFrom(other.key_data());
      }
      status_.set_value(other.status());
      key_id_.set_value(other.key_id());
      output_prefix_type_.set_value(other.output_prefix_type());
    }

    void CopyFrom(const KeyTP& other) {
      if (this == &other) {
        return;
      }
      Clear();
      MergeFrom(other);
    }

   private:
    size_t num_fields() const override { return 4; }
    const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
      return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                        4>{&key_data_, &status_, &key_id_, &output_prefix_type_}[i];
    }

    ::crypto::tink::internal::proto_parsing::MessageField<::google::crypto::tink::internal::KeyDataTP> key_data_{1, ::crypto::tink::internal::ProtoFieldOptions::kExplicit};
    ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::KeyStatusTypeTP> status_{
        2, &::google::crypto::tink::internal::KeyStatusTypeTP_IsValid, ::google::crypto::tink::internal::KeyStatusTypeTP::kUnknownStatus,
        ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
    ::crypto::tink::internal::proto_parsing::Uint32Field key_id_{3, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
    ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::OutputPrefixTypeTP> output_prefix_type_{
        4, &::google::crypto::tink::internal::OutputPrefixTypeTP_IsValid, ::google::crypto::tink::internal::OutputPrefixTypeTP::kUnknownPrefix,
        ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  };
  KeysetTP() = default;

  KeysetTP(KeysetTP&&) = default;
  KeysetTP& operator=(KeysetTP&&) = default;
  KeysetTP(const KeysetTP&) = default;
  KeysetTP& operator=(const KeysetTP&) = default;

  void clear_primary_key_id() {
    primary_key_id_.Clear();
  }
  uint32_t primary_key_id() const {
    return primary_key_id_.value();
  }
  void set_primary_key_id(uint32_t value) {
    primary_key_id_.set_value(value);
  }

  int key_size() const {
    return key_.values_size();
  }
  void clear_key() { key_.Clear(); }
  ::google::crypto::tink::internal::KeysetTP::KeyTP* add_key() {
    return key_.add_values();
  }
  std::vector<::google::crypto::tink::internal::KeysetTP::KeyTP>* mutable_key() {
    return key_.mutable_values();
  }
  ::google::crypto::tink::internal::KeysetTP::KeyTP* mutable_key(int index) {
    return key_.mutable_values(index);
  }
  const ::google::crypto::tink::internal::KeysetTP::KeyTP& key(int index) const {
    return key_.values(index);
  }
  const std::vector<::google::crypto::tink::internal::KeysetTP::KeyTP>& key() const {
    return key_.values();
  }

  void MergeFrom(const KeysetTP& other) {
    primary_key_id_.set_value(other.primary_key_id());
    mutable_key()->insert(
        key_.values().end(),
        other.key().begin(),
        other.key().end());
  }

  void CopyFrom(const KeysetTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 2; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      2>{&primary_key_id_, &key_}[i];
  }

  ::crypto::tink::internal::proto_parsing::Uint32Field primary_key_id_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::RepeatedMessageField<::google::crypto::tink::internal::KeysetTP::KeyTP>
      key_{2};
};
class KeysetInfoTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  class KeyInfoTP : public ::crypto::tink::internal::proto_parsing::Message {
   public:
    KeyInfoTP() = default;

    KeyInfoTP(KeyInfoTP&&) = default;
    KeyInfoTP& operator=(KeyInfoTP&&) = default;
    KeyInfoTP(const KeyInfoTP&) = default;
    KeyInfoTP& operator=(const KeyInfoTP&) = default;

    void clear_type_url() {
      type_url_.Clear();
    }
    std::string* mutable_type_url() {
      return type_url_.mutable_value();
    }
    const std::string& type_url() const {
      return type_url_.value();
    }
    void set_type_url(absl::string_view value) {
      type_url_.set_value(value);
    }

    void clear_status() {
      status_.Clear();
    }
    ::google::crypto::tink::internal::KeyStatusTypeTP status() const {
      return status_.value();
    }
    void set_status(::google::crypto::tink::internal::KeyStatusTypeTP value) {
      status_.set_value(value);
    }

    void clear_key_id() {
      key_id_.Clear();
    }
    uint32_t key_id() const {
      return key_id_.value();
    }
    void set_key_id(uint32_t value) {
      key_id_.set_value(value);
    }

    void clear_output_prefix_type() {
      output_prefix_type_.Clear();
    }
    ::google::crypto::tink::internal::OutputPrefixTypeTP output_prefix_type() const {
      return output_prefix_type_.value();
    }
    void set_output_prefix_type(::google::crypto::tink::internal::OutputPrefixTypeTP value) {
      output_prefix_type_.set_value(value);
    }

    void MergeFrom(const KeyInfoTP& other) {
      type_url_.set_value(other.type_url());
      status_.set_value(other.status());
      key_id_.set_value(other.key_id());
      output_prefix_type_.set_value(other.output_prefix_type());
    }

    void CopyFrom(const KeyInfoTP& other) {
      if (this == &other) {
        return;
      }
      Clear();
      MergeFrom(other);
    }

   private:
    size_t num_fields() const override { return 4; }
    const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
      return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                        4>{&type_url_, &status_, &key_id_, &output_prefix_type_}[i];
    }

    ::crypto::tink::internal::proto_parsing::BytesField type_url_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
    ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::KeyStatusTypeTP> status_{
        2, &::google::crypto::tink::internal::KeyStatusTypeTP_IsValid, ::google::crypto::tink::internal::KeyStatusTypeTP::kUnknownStatus,
        ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
    ::crypto::tink::internal::proto_parsing::Uint32Field key_id_{3, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
    ::crypto::tink::internal::proto_parsing::EnumField<::google::crypto::tink::internal::OutputPrefixTypeTP> output_prefix_type_{
        4, &::google::crypto::tink::internal::OutputPrefixTypeTP_IsValid, ::google::crypto::tink::internal::OutputPrefixTypeTP::kUnknownPrefix,
        ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  };
  KeysetInfoTP() = default;

  KeysetInfoTP(KeysetInfoTP&&) = default;
  KeysetInfoTP& operator=(KeysetInfoTP&&) = default;
  KeysetInfoTP(const KeysetInfoTP&) = default;
  KeysetInfoTP& operator=(const KeysetInfoTP&) = default;

  void clear_primary_key_id() {
    primary_key_id_.Clear();
  }
  uint32_t primary_key_id() const {
    return primary_key_id_.value();
  }
  void set_primary_key_id(uint32_t value) {
    primary_key_id_.set_value(value);
  }

  int key_info_size() const {
    return key_info_.values_size();
  }
  void clear_key_info() { key_info_.Clear(); }
  ::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP* add_key_info() {
    return key_info_.add_values();
  }
  std::vector<::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP>* mutable_key_info() {
    return key_info_.mutable_values();
  }
  ::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP* mutable_key_info(int index) {
    return key_info_.mutable_values(index);
  }
  const ::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP& key_info(int index) const {
    return key_info_.values(index);
  }
  const std::vector<::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP>& key_info() const {
    return key_info_.values();
  }

  void MergeFrom(const KeysetInfoTP& other) {
    primary_key_id_.set_value(other.primary_key_id());
    mutable_key_info()->insert(
        key_info_.values().end(),
        other.key_info().begin(),
        other.key_info().end());
  }

  void CopyFrom(const KeysetInfoTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 2; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      2>{&primary_key_id_, &key_info_}[i];
  }

  ::crypto::tink::internal::proto_parsing::Uint32Field primary_key_id_{1, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::RepeatedMessageField<::google::crypto::tink::internal::KeysetInfoTP::KeyInfoTP>
      key_info_{2};
};
class EncryptedKeysetTP : public ::crypto::tink::internal::proto_parsing::Message {
 public:
  EncryptedKeysetTP() = default;

  EncryptedKeysetTP(EncryptedKeysetTP&&) = default;
  EncryptedKeysetTP& operator=(EncryptedKeysetTP&&) = default;
  EncryptedKeysetTP(const EncryptedKeysetTP&) = default;
  EncryptedKeysetTP& operator=(const EncryptedKeysetTP&) = default;

  void clear_encrypted_keyset() {
    encrypted_keyset_.Clear();
  }
  std::string* mutable_encrypted_keyset() {
    return encrypted_keyset_.mutable_value();
  }
  const std::string& encrypted_keyset() const {
    return encrypted_keyset_.value();
  }
  void set_encrypted_keyset(absl::string_view value) {
    encrypted_keyset_.set_value(value);
  }

  bool has_keyset_info() const {
    return keyset_info_.has_value();
  }
  void clear_keyset_info() {
    keyset_info_.Clear();
  }
  ::google::crypto::tink::internal::KeysetInfoTP* mutable_keyset_info() {
    return keyset_info_.mutable_value();
  }
  const ::google::crypto::tink::internal::KeysetInfoTP& keyset_info() const {
    return keyset_info_.value();
  }

  void MergeFrom(const EncryptedKeysetTP& other) {
    encrypted_keyset_.set_value(other.encrypted_keyset());
    if (other.has_keyset_info()) {
      keyset_info_.mutable_value()->MergeFrom(other.keyset_info());
    }
  }

  void CopyFrom(const EncryptedKeysetTP& other) {
    if (this == &other) {
      return;
    }
    Clear();
    MergeFrom(other);
  }

 private:
  size_t num_fields() const override { return 2; }
  const ::crypto::tink::internal::proto_parsing::Field* field(int i) const override {
    return std::array<const ::crypto::tink::internal::proto_parsing::Field*,
                      2>{&encrypted_keyset_, &keyset_info_}[i];
  }

  ::crypto::tink::internal::proto_parsing::BytesField encrypted_keyset_{2, ::crypto::tink::internal::ProtoFieldOptions::kImplicit};
  ::crypto::tink::internal::proto_parsing::MessageField<::google::crypto::tink::internal::KeysetInfoTP> keyset_info_{3, ::crypto::tink::internal::ProtoFieldOptions::kExplicit};
};
}  // namespace google::crypto::tink::internal

// clang-format on
// NOLINTEND

#endif  // THIRD_PARTY_TINK_PROTO_TINK_TINKPB_H_
