load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

licenses(["notice"])

cc_library(
    name = "aead_test_vector",
    hdrs = ["aead_test_vector.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        "//tink/aead:aead_key",
        "@abseil-cpp//absl/strings:string_view",
    ],
)

cc_library(
    name = "aes_gcm_test_vectors",
    srcs = ["aes_gcm_test_vectors.cc"],
    hdrs = ["aes_gcm_test_vectors.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        ":aead_test_vector",
        "//tink:insecure_secret_key_access",
        "//tink:partial_key_access",
        "//tink:restricted_data",
        "//tink/aead:aes_gcm_key",
        "//tink/aead:aes_gcm_parameters",
        "//tink/util:test_util",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
    ],
)

cc_library(
    name = "aes_eax_test_vectors",
    testonly = True,
    srcs = ["aes_eax_test_vectors.cc"],
    hdrs = ["aes_eax_test_vectors.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        ":aead_test_vector",
        "//tink:insecure_secret_key_access",
        "//tink:partial_key_access",
        "//tink:restricted_data",
        "//tink/aead:aes_eax_key",
        "//tink/aead:aes_eax_parameters",
        "//tink/util:test_util",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
    ],
)

cc_library(
    name = "aes_ctr_hmac_aead_test_vectors",
    testonly = True,
    srcs = ["aes_ctr_hmac_aead_test_vectors.cc"],
    hdrs = ["aes_ctr_hmac_aead_test_vectors.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        ":aead_test_vector",
        "//tink:insecure_secret_key_access",
        "//tink:partial_key_access",
        "//tink:restricted_data",
        "//tink/aead:aes_ctr_hmac_aead_key",
        "//tink/aead:aes_ctr_hmac_aead_parameters",
        "//tink/subtle:aes_ctr_boringssl",
        "//tink/subtle:common_enums",
        "//tink/subtle:encrypt_then_authenticate",
        "//tink/subtle:hmac_boringssl",
        "//tink/util:secret_data",
        "//tink/util:test_util",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
    ],
)

cc_library(
    name = "aes_gcm_siv_test_vectors",
    testonly = True,
    srcs = ["aes_gcm_siv_test_vectors.cc"],
    hdrs = ["aes_gcm_siv_test_vectors.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        ":aead_test_vector",
        "//tink:insecure_secret_key_access",
        "//tink:partial_key_access",
        "//tink:restricted_data",
        "//tink/aead:aes_gcm_siv_key",
        "//tink/aead:aes_gcm_siv_parameters",
        "//tink/util:test_util",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
    ],
)

cc_library(
    name = "x_aes_gcm_test_vectors",
    testonly = True,
    srcs = ["x_aes_gcm_test_vectors.cc"],
    hdrs = ["x_aes_gcm_test_vectors.h"],
    include_prefix = "tink/aead/internal/testing",
    deps = [
        ":aead_test_vector",
        "//tink:insecure_secret_key_access",
        "//tink:partial_key_access",
        "//tink:restricted_data",
        "//tink/aead:x_aes_gcm_key",
        "//tink/aead:x_aes_gcm_parameters",
        "//tink/aead/internal:cord_x_aes_gcm_boringssl",
        "//tink/util:test_util",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:cord",
        "@abseil-cpp//absl/strings:string_view",
        "@abseil-cpp//absl/types:optional",
    ],
)
